import Head from "next/head";
import HomeHeader from "../components/Home/HomeHeader";
import LatestAlerts from "../components/Home/LatestAlerts/LatestAlerts";
import RiskBreakDown from "../components/Home/RiskBreakDown/RiskBreakDown";
import Trend from "../components/Home/Trend/Trend";
import SearchInput from "../components/SearchInput";
import { GetCountries } from "../services/countriesService";
import styles from "../styles/Home.module.scss";
import { useState, useEffect } from "react";
export default function Home() {
  const [countries, setCountries] = useState([]);
  useEffect(async () => {
    const countiesData = await GetCountries();
    setCountries(countiesData.countries);
  }, []);
  return (
    <div className={`${styles.homeContainer} `}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"container"}>
        <HomeHeader></HomeHeader>
        <div className={styles.grid}>
          <div className={styles.searchInput}>
            <SearchInput list={"countries"} data={countries}></SearchInput>
          </div>
          <div className={styles.reports}>
            <LatestAlerts></LatestAlerts>
            <div className={styles.trendAndRiskContainer}>
              <div className={styles.trendContainer}>
                <Trend></Trend>
              </div>
              <div className={styles.riskBreakDownContainer}>
                <RiskBreakDown></RiskBreakDown>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
